version: "3.8"

services:
  api:
    container_name: api
    env_file:
      - ./.env
    build: ./
    image: poc_pdtec_image
    volumes:
      - ./:/home/poc_pdtec/
    ports:
      - 8000:8000
    command: >
      python -m
        uvicorn
        entrypoints.web.main:app
        --loop 'uvloop'
        --http 'httptools'
        --log-level debug
        --reload
        --workers 1
        --host 0.0.0.0
        --port 8000
