version: "3.8"

services:
  api:
    container_name: api
    env_file:
      - ./.env
    build: ./
    image: atualiza-parceiro-image
    volumes:
      - ./:/home/atualiza-parceiro/
    ports:
      - 8000:8000
    command: >
      python -m
        uvicorn
        --factory
        entrypoints.web.main:create_app
        --loop 'uvloop'
        --http 'httptools'
        --log-level info
        --reload
        --workers 1
        --host 0.0.0.0
        --port 8000
    depends_on:
      - db
  db:
    image: postgres:alpine3.14
    ports:
      - 54321:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
